---
title: "Questionaire"
author: "PB"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Rﺣ۸gression Simple

### Modﺣ۷le

1.  Les $\epsilon_i$ sont alﺣ۸atoires
    a.  Oui
    b.  Non
2.  Les $x_i$ sont alﺣ۸atoires
    a.  Oui
    b.  Non
3.  Les $y_i$ sont alﺣ۸atoires
    a.  Oui
    b.  Non
4.  Les $\beta_i$ sont alﺣ۸atoires
    a.  Oui
    b.  Non
5.  Les $\epsilon_i$ sont indﺣ۸pendants
    a.  Oui
    b.  Non

### Variances

1.  Lorsque les $x_i$ sont plus ﺣ۸talﺣ۸s, la variance de $\hat{\beta}_0$
    est :
    a.  plus grande
    b.  plus petite
    c.  indﺣ۸terminﺣ۸
2.  Lorsque les $x_i$ sont plus ﺣ۸talﺣ۸s, la variance de $\hat{\beta}_1$
    est :
    a.  plus grande
    b.  plus petite
    c.  indﺣ۸terminﺣ۸
3.  L'estimateur des moindres carrﺣ۸s est l'estimateur qui a la plus
    petite variance.
    a.  Vrai
    b.  Faux
    c.  Indﺣ۸terminﺣ۸
4.  Si $R^2$ est proche de 1, les $y_i$ sont ﺣ  peu prﺣ۷s rﺣ۸partis sur une
    droite en fonction des $x_i$
    a.  Vrai
    b.  Faux
    c.  Indﺣ۸terminﺣ۸

## Rﺣ۸gression Simple Gaussienne

### Modﺣ۷le

1.  Les $\epsilon_i$ sont gaussiens
    a.  Oui
    b.  Non
2.  Les $x_i$ sont gaussiens
    a.  Oui
    b.  Non
3.  Les $y_i$ sont gaussiens
    a.  Oui
    b.  Non
4.  Les $\beta_i$ sont gaussiens
    a.  Oui
    b.  Non
5.  Les $\epsilon_i$ sont indﺣ۸pendants
    a.  Oui
    b.  Non

### Estimateurs

1.  Les estimateurs du maximum de vraisemblance $\hat{\beta}_0$ et
    $\hat{\beta}_1$ sont non biaisﺣ۸s
    a.  Oui
    b.  Non
2.  L'estimateur du maximum de vraisemblance de la variance
    $\hat{\sigma}^2$ est non biaisﺣ۸
    a.  Oui
    b.  Non
3.  Les estimateurs du maximum de vraisemblance $\hat{\beta}_0$ et
    $\hat{\beta}_1$ sont les estimateurs avec la plus petite variance
    parmi les estimateurs linﺣ۸aires
    a.  Oui
    b.  Non

### Distribution des estimateurs - variance connue

On se place dans le cadre du modﺣ۷le gaussien, avec variance **connue**.

1.  Lorsque la variance est connue, les estimateurs $\hat{\beta}_0$ et
    $\hat{\beta}_1$ sont gaussiens
    a.  Oui
    b.  Non
2.  Lorsque la variance est connue, les estimateurs $\hat{\beta}_0$ et
    $\hat{\beta}_1$ sont indﺣ۸pendants
    a.  Oui
    b.  Non
3.  Lorsque la variance est connue, l'estimateur (des moindres carrﺣ۸s)
    $\hat{\sigma}^2$ est gaussien
    a.  Oui
    b.  Non

### Distribution des estimateurs - variance inconnue

On se place dans le cadre du modﺣ۷le gaussien, avec variance
**inconnue**.

1.  Lorsque la variance est inconnue, les estimateurs $\hat{\beta}_0$ et
    $\hat{\beta}_1$ sont biaisﺣ۸s
    a.  Oui
    b.  Non
2.  Lorsque la variance est inconnue, les estimateurs $\hat{\beta}_0$ et
    $\hat{\beta}_1$ sont gaussiens
    a.  Oui
    b.  Non
3.  Lorsque la variance est inconnue, les estimateurs $\hat{\beta}_0$ et
    $\hat{\beta}_1$ sont indﺣ۸pendants
    a.  Oui
    b.  Non

## Rﺣ۸gression Multiple

### Modﺣ۷le

On considﺣ۷re le modﺣ۷le
$\mathbf{y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\epsilon}$
avec $n$ observations et $p$ prﺣ۸dicteurs.

1.  Quelle est la dimension de $\mathbf{X}$ ?
    a.  $p \times p$
    b.  $n \times p$
    c.  $p \times n$
2.  Quelle est la dimension de $\mathbf{y}$ ?
    a.  $p \times 1$
    b.  $n \times 1$
    c.  $1 \times n$
    d.  $1 \times p$
3.  Quelle est la dimension de $\boldsymbol{\beta}$ ?
    a.  $p \times 1$
    b.  $n \times 1$
    c.  $1 \times n$
    d.  $1 \times p$
4.  Quelle est la dimension de $\boldsymbol{\epsilon}$ ?
    a.  $p \times 1$
    b.  $n \times 1$
    c.  $1 \times n$
    d.  $1 \times p$
5.  Quelle est la dimension de $\mathbf{x}_i$ la i$^{ﺣ۷me}$ colonne de
    $\mathbf{X}$ ?
    a.  $p \times 1$
    b.  $n \times 1$
    c.  $1 \times n$
    d.  $1 \times p$
6.  Quelle est la dimension de $\mathbf{x}^i$ la i$^{ﺣ۷me}$ ligne de
    $\mathbf{X}$ ?
    a.  $p \times 1$
    b.  $n \times 1$
    c.  $1 \times n$
    d.  $1 \times p$
7.  Lesquelles de ces formules sont correctes ?
    a.  $y_i = \mathbf{x}_i \boldsymbol{\beta} + \epsilon_i$
    b.  $y_i = \mathbf{x}^i \boldsymbol{\beta} + \epsilon_i$
    c.  $\mathbf{y} = \sum_{k = 1}^p \beta_k \mathbf{x}_k + \boldsymbol{\epsilon}$
    d.  $\mathbf{y} = \sum_{k = 1}^p \beta_k \mathbf{x}^k + \boldsymbol{\epsilon}$

### Degrﺣ۸s de libertﺣ۸s

1.  Dans une rﺣ۸gression simple
    $y_i = \beta_0 + \beta_1 x_i + \epsilon_i$ combien y a t il de
    **variables explicatives** ? (En supposant les vecteurs $\mathbf{1}$
    et $\mathbf{x}$ indﺣ۸pendants.)
    a.  $1$
    b.  $2$
    c.  $3$
    d.  $4$
2.  Dans une rﺣ۸gression simple
    $y_i = \beta_0 + \beta_1 x_i + \epsilon_i$ combien y a t il de
    **degrﺣ۸s de libertﺣ۸** ? (En supposant les vecteurs $\mathbf{1}$ et
    $\mathbf{x}$ indﺣ۸pendants.)
    a.  $n - 1$
    b.  $n - 2$
    c.  $n - 3$
    d.  $n - 4$
3.  Dans une rﺣ۸gression multiple
    $y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \epsilon_i$
    combien y a t il de **variables explicatives** ? (En supposant les
    vecteurs $\mathbf{1}$ et $\mathbf{x}_1$ et $\mathbf{x}_2$
    indﺣ۸pendants.)
    a.  $1$
    b.  $2$
    c.  $3$
    d.  $4$
4.  Dans une rﺣ۸gression multiple
    $y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \epsilon_i$
    combien y a t il de **degrﺣ۸s de libertﺣ۸** ? (En supposant les
    vecteurs $\mathbf{1}$ et $\mathbf{x}_1$ et $\mathbf{x}_2$
    indﺣ۸pendants.)
    a.  $n - 1$
    b.  $n - 2$
    c.  $n - 3$
    d.  $n - 4$
5.  Dans une rﺣ۸gression multiple
    $y_i = \beta_1 x_{i1} + \beta_2 x_{i2} + \epsilon_i$ combien y a t
    il de **variables explicatives** ? (En supposant les vecteurs
    $\mathbf{x}_1$ et $\mathbf{x}_2$ indﺣ۸pendants.)
    a.  $1$
    b.  $2$
    c.  $3$
    d.  $4$
6.  Dans une rﺣ۸gression multiple
    $y_i = \beta_1 x_{i1} + \beta_2 x_{i2} + \epsilon_i$ combien y a t
    il de **degrﺣ۸s de libertﺣ۸** ? (En supposant les vecteurs
    $\mathbf{x}_1$ et $\mathbf{x}_2$ indﺣ۸pendants.)
    a.  $n - 1$
    b.  $n - 2$
    c.  $n - 3$
    d.  $n - 4$

### Projections

1.  Dans le modﺣ۷le matriciel
    $\mathbf{y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\epsilon}$,
    l'estimateur des moindres carrﺣ۸s $\hat{\boldsymbol{\beta}}$ est la
    projection de $\mathbf{y}$ sur l'espace engendrﺣ۸ par les lignes de
    $\mathbf{X}$.
    a.  Oui
    b.  Non
2.  Dans le modﺣ۷le matriciel
    $\mathbf{y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\epsilon}$,
    l'estimateur des moindres carrﺣ۸s $\hat{\boldsymbol{\beta}}$ est la
    projection de $\mathbf{y}$ sur l'espace engendrﺣ۸ par les colonnes de
    $\mathbf{X}$.
    a.  Oui
    b.  Non
3.  Dans le modﺣ۷le matriciel
    $\mathbf{y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\epsilon}$,
    le prﺣ۸dicteur
    $\hat{\mathbf{y}} = \mathbf{X}\hat{\boldsymbol{\beta}}$ est la
    projection de $\mathbf{y}$ sur l'espace engendrﺣ۸ par les colonnes de
    $\mathbf{X}$.
    a.  Oui
    b.  Non
4.  Dans le modﺣ۷le matriciel
    $\mathbf{y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\epsilon}$,
    le prﺣ۸dicteur
    $\hat{\mathbf{y}} = \mathbf{X}\hat{\boldsymbol{\beta}}$ est la
    projection de $\mathbf{y}$ sur l'espace engendrﺣ۸ par les lignes de
    $\mathbf{X}$.
    a.  Oui
    b.  Non

### Matrices de projection

1.  Soit $\mathbf{P}^\mathbf{X}$ la matrice de projection orthogonale
    sur l'espace engendrﺣ۸ par les colonnes de $\mathbf{X}$. Alors :
    $\mathbf{P}^\mathbf{X} \mathbf{P}^\mathbf{X} = \mathbf{P}^\mathbf{X}$.
    a.  Oui
    b.  Non
2.  $\mathbf{P}^\mathbf{X}$ est symﺣ۸trique.
    a.  Oui
    b.  Non
3.  Si $p$ est le rang de la matrice $\mathbf{X}$, la trace de
    $\mathbf{P}^\mathbf{X}$ vaut
    a.  $p$
    b.  $n-p$
4.  $\mathbf{P}^\mathbf{X} \mathbf{y}$ est ﺣ۸gal ﺣ 
    a.  $\hat{\boldsymbol{\beta}}$
    b.  $\hat{\mathbf{y}}$
    c.  aucun des deux

## Estimateur

1.  $\hat{\boldsymbol{\beta}}=$
    a.  $(\mathbf{X}\mathbf{X}^{T})^{-1}\mathbf{X}^{T}\mathbf{y}$
    b.  $(\mathbf{X}\mathbf{X}^{T})^{-1}\mathbf{X}\mathbf{y}$
    c.  $(\mathbf{X}^{T}\mathbf{X})^{-1}\mathbf{X}^{T}\mathbf{y}$
    d.  $(\mathbf{X}^{T}\mathbf{X})^{-1}\mathbf{X}\mathbf{y}$

### $R^2$

1.  Un modﺣ۷le avec plus de variables a toujours un $R^2$ plus grand
    qu'un modﺣ۷le avec moins de variables.
    a.  Oui
    b.  Non
2.  Un modﺣ۷le avec un $R^2$ plus grand est toujours meilleur qu'un
    modﺣ۷le avec un $R^2$ plus petit.
    a.  Oui
    b.  Non

## Rﺣ۸gression Multiple Gaussienne

### Loi des estimateurs

1.  Lorsque la variance est connue, l'estimateur
    $\hat{\boldsymbol{\beta}}$ est un vecteur gaussien.
    a.  Oui
    b.  Non
2.  Lorsque la variance est connue, l'estimateur
    $\hat{\boldsymbol{\beta}}$ est biaisﺣ۸.
    a.  Oui
    b.  Non
3.  Lorsque la variance est connue, l'estimateur $\hat{\sigma}^2$ est
    a.  un vecteur
    b.  un scalaire
4.  Lorsque la variance est connue, l'estimateur $\hat{\sigma}^2$ des
    moindres carrﺣ۸s est biaisﺣ۸.
    a.  Oui
    b.  Non
5.  Lorsque la variance est connue, l'estimateur $\hat{\sigma}^2$ des
    moindres carrﺣ۸s, normalisﺣ۸, suit:
    a.  une loi de Student ﺣ  $p$ degrﺣ۸s de libertﺣ۸s
    b.  une loi de Student ﺣ  $n-p$ degrﺣ۸s de libertﺣ۸s
    c.  une loi du chi deux ﺣ  $p$ degrﺣ۸s de libertﺣ۸s
    d.  une loi du chi deux ﺣ  $n-p$ degrﺣ۸s de libertﺣ۸s
6.  $\hat{\boldsymbol{\beta}}$ et $\hat{\sigma}^2$ sont indﺣ۸pendants.
    a.  Oui
    b.  Non

### Test de Fisher global

1.  Pour un test de Fisher global, l'hypothﺣ۷se nulle est :
    a.  $\exists~ k ~|~ \beta_k = 0$
    b.  $\exists~ k ~|~ \beta_k \neq 0$
    c.  $\forall~ k, \beta_k = 0$
    d.  $\forall~ k, \beta_k \neq 0$
2.  Pour un test de Fisher global, l'hypothﺣ۷se alternative est :
    a.  $\exists~ k ~|~ \beta_k = 0$
    b.  $\exists~ k ~|~ \beta_k \neq 0$
    c.  $\forall~ k, \beta_k = 0$
    d.  $\forall~ k, \beta_k \neq 0$
3.  Qualitativement, lorsque l'erreur
    $\| \hat{\boldsymbol{\epsilon}} \|^2$ est grande, la statistique de
    test $F$ est :
    a.  plutﺣﺑt grande
    b.  plutﺣﺑt petite
4.  Qualitativement, lorsque l'erreur
    $\| \hat{\boldsymbol{\epsilon}} \|^2$ est grande :
    a.  on a tendance ﺣ  rejeter l'hypothﺣ۷se nulle
    b.  on a tendance ﺣ  ne pas rejeter l'hypothﺣ۷se nulle
5.  Sous l'hypothﺣ۷se nulle, la statistique de test $F$ suit la loi :
    a.  $\mathcal{F}(p, n-p)$
    b.  $\mathcal{T}(p)$
    c.  $\chi^2(n-p)$

### Test de Fisher emboﺣ؟tﺣ۸

On rﺣ۸alise un test de Fisher emboﺣ؟tﺣ۸ sur les deux modﺣ۷les :
$\mathbf{y} = \mathbf{X}_0 \boldsymbol{\beta}_0 + \boldsymbol{\epsilon}_0$
et $\mathbf{y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\epsilon}$,
oﺣﺗ $\mathbf{X}_0$ est une sous-matrice de $\mathbf{X}$.

1.  Si je rejette H_0, cela signifie :
    a.  que le modﺣ۷le reprﺣ۸sentﺣ۸ par $\mathbf{X}_0$ est suffisant
    b.  que le modﺣ۷le reprﺣ۸sentﺣ۸ par $\mathbf{X}_0$ n'est pas suffisant
2.  La statistique de test vaut ;
    a.  $\frac{RSS - RSS_0}{RSS}$
    b.  $\frac{(RSS - RSS_0)/ (p - p_0)}{RSS / p}$
    c.  $\frac{(RSS - RSS_0) / (p - p_0)}{RSS / (n - p)}$
    d.  $\frac{RSS_0 - RSS}{RSS}$
    e.  $\frac{(RSS_0 - RSS)/ (p - p_0)}{RSS / p}$
    f.  $\frac{(RSS_0 - RSS) / (p - p_0)}{RSS / (n - p)}$
3.  Sa distribution sous l'hypothﺣ۷se nulle est :
    a.  $\mathcal{F}(p, n-p)$
    b.  $\mathcal{F}(p_0, n-p)$
    c.  $\mathcal{F}(p - p_0, n-p)$
    d.  $\mathcal{F}(p - p_0, n-p_0)$

### $F$ Statistic

On considﺣ۷re la "$F$ statistic" renvoyﺣ۸e par `R` :

1.  Cette statistique reprﺣ۸sente la statistique d'un test de Fisher
    emboﺣ؟tﺣ۸ :
    a.  oui
    b.  non
2.  Sous l'hypothﺣ۷se nulle correspondante :
    a.  le modﺣ۷le est complet
    b.  le modﺣ۷le comporte uniquement l'intercepte
    c.  le modﺣ۷le est vide (tous les coefficients sont nuls)

## Sﺣ۸lection de variables

### Risque prﺣ۸dictif

1.  Si j'ajoute des variables au modﺣ۷le, celui-ci s'ajuste mieux aux
    donnﺣ۸es
    a.  Oui
    b.  Non
    c.  Indﺣ۸terminﺣ۸
2.  Si j'ajoute des variables au modﺣ۷le, celui-ci est plus performant
    pour prﺣ۸dire de nouveaux points
    a.  Oui
    b.  Non
    c.  Indﺣ۸terminﺣ۸

### Critﺣ۷res de sﺣ۸lection

1.  On sﺣ۸lection un modﺣ۷le avec un $R^2$
    a.  le plus grand possible
    b.  le plus petit possible
    c.  indﺣ۸terminﺣ۸
2.  On sﺣ۸lection un modﺣ۷le avec un $R^2_a$
    a.  le plus grand possible
    b.  le plus petit possible
    c.  indﺣ۸terminﺣ۸
3.  On sﺣ۸lection une vraisemblance maximisﺣ۸e
    a.  la plus grande possible
    b.  la plus petite possible
    c.  indﺣ۸terminﺣ۸
4.  On sﺣ۸lection un AIC
    a.  le plus grand possible
    b.  le plus petit possible
    c.  indﺣ۸terminﺣ۸
5.  On sﺣ۸lection un BIC
    a.  le plus grand possible
    b.  le plus petit possible
    c.  indﺣ۸terminﺣ۸
6.  On sﺣ۸lection un $C_p$ de Mallow
    a.  le plus grand possible
    b.  le plus petit possible
    c.  indﺣ۸terminﺣ۸

### Critﺣ۷res de sﺣ۸lection

1.  Pour un modﺣ۷le avec $k$ variables, AIC =
    a.  $2\log \hat{L} + 2 k$
    b.  $2\log \hat{L} - 2 k$
    c.  $- 2\log \hat{L} + 2 k$
    d.  $- 2\log \hat{L} - 2 k$
2.  Pour un modﺣ۷le avec $k$ variables, BIC =
    a.  $- 2\log \hat{L} + 2 k \log(n)$
    b.  $- 2\log \hat{L} + k \log(n)$
    c.  $- \log \hat{L} +  k \log(n)$

## Validation

### Rﺣ۸sidus

1.  Sous l'hypothﺣ۷se Gaussienne, les rﺣ۸sidus
    $\hat{\epsilon}_i = y_i - \hat{y}_i$ sont identiquement distribuﺣ۸s.
    a.  Oui
    b.  Non
    c.  Indﺣ۸terminﺣ۸
2.  Sous l'hypothﺣ۷se Gaussienne, les rﺣ۸sidus studentisﺣ۸s $t^*_i$ sont
    identiquement distribuﺣ۸s.
    a.  Oui
    b.  Non
    c.  Indﺣ۸terminﺣ۸
3.  Sous l'hypothﺣ۷se Gaussienne, les rﺣ۸sidus normalisﺣ۸s $t_i$ suivent
    une loi de Student ﺣ 
    a.  $p$ degrﺣ۸s de libertﺣ۸s
    b.  $n - p$ degrﺣ۸s de libertﺣ۸s
    c.  $n - 1$ degrﺣ۸s de libertﺣ۸s
    d.  $n - p - 1$ degrﺣ۸s de libertﺣ۸s
    e.  pas une loi de Student
4.  Sous l'hypothﺣ۷se Gaussienne, les rﺣ۸sidus studentisﺣ۸s $t_i^*$ suivent
    une loi de Student ﺣ 
    a.  $p$ degrﺣ۸s de libertﺣ۸s
    b.  $n - p$ degrﺣ۸s de libertﺣ۸s
    c.  $n - 1$ degrﺣ۸s de libertﺣ۸s
    d.  $n - p - 1$ degrﺣ۸s de libertﺣ۸s
    e.  pas une loi de Student

### Intervalles de confiance

1.  Si les rﺣ۸sidus sont centrﺣ۸s iid, on peut calculer la variance des
    estimateurs $\hat{\beta}$
    a.  Oui
    b.  Non
    c.  Indﺣ۸terminﺣ۸
2.  Si les rﺣ۸sidus sont centrﺣ۸s iid de variance finie, on peut calculer
    la variance des estimateurs $\hat{\beta}$
    a.  Oui
    b.  Non
    c.  Indﺣ۸terminﺣ۸
3.  Si les rﺣ۸sidus sont centrﺣ۸s iid de variance finie, on peut calculer
    un intervalle de confiance pour les estimateurs $\hat{\beta}$
    a.  Oui, exact
    b.  Oui, approchﺣ۸
    c.  Non
    d.  Indﺣ۸terminﺣ۸
4.  Si les rﺣ۸sidus sont centrﺣ۸s iid gaussiens, on peut calculer un
    intervalle de confiance pour les estimateurs $\hat{\beta}$
    a.  Oui, exact
    b.  Oui, approchﺣ۸
    c.  Non
    d.  Indﺣ۸terminﺣ۸

### Points de leviers et aberrants

1.  Un point aberrant (outlier) est toujours un point levier (high
    leverage)
    a.  Oui
    b.  Non
2.  Un point levier (outlier) est toujours un point aberrant (high
    leverage)
    a.  Oui
    b.  Non
3.  Lorsque l'on retire un point aberrant de l'analyse, la droite de
    rﺣ۸gression change significativement
    a.  Oui
    b.  Non
4.  Lorsque l'on retire un point de distance de Cook ﺣ۸levﺣ۸e de
    l'analyse, la droite de rﺣ۸gression change significativement
    a.  Oui
    b.  Non

## ANOVA

1.  Dans l'ANOVA ﺣ  un facteur, combien y-a-t-il de groupes diffﺣ۸rents ?
    a.  1
    b.  2
    c.  3
    d.  4
    e.  plus
    f.  Indﺣ۸terminﺣ۸
2.  Dans l'ANOVA ﺣ  deux facteurs, combien y-a-t-il de groupes diffﺣ۸rents
    ?
    a.  1
    b.  2
    c.  3
    d.  4
    e.  plus
    f.  Indﺣ۸terminﺣ۸
3.  Dans l'ANOVA ﺣ  un facteur, peut-on prendre des effets d'interactions
    en compte ?
    a.  Oui
    b.  Non
4.  Dans l'ANOVA ﺣ  deux facteurs, peut-on prendre des effets
    d'interactions en compte ?
    a.  Oui
    b.  Non
5.  Dans l'ANCOVA, peut-on prendre des effets d'interactions en compte ?
    a.  Oui
    b.  Non
6.  Pour une ANOVA ﺣ  deux facteurs, la table de "Type I" traite les deux
    facteurs de maniﺣ۷re symﺣ۸trique.
    a.  Oui
    b.  Non
